insert into Categoria (id, name, description) values (1, 'Finance', 'seize transparent paradigms');
insert into Categoria (id, name, description) values (2, 'Health Care', 'engage strategic synergies');
insert into Categoria (id, name, description) values (3, 'n/a', 'engage revolutionary channels');
insert into Categoria (id, name, description) values (4, 'n/a', 'redefine out-of-the-box infomediaries');
insert into Categoria (id, name, description) values (5, 'n/a', 'e-enable magnetic initiatives');
insert into Categoria (id, name, description) values (6, 'Consumer Services', 'exploit impactful portals');
insert into Categoria (id, name, description) values (7, 'Consumer Services', 'syndicate world-class deliverables');
insert into Categoria (id, name, description) values (8, 'Consumer Services', 'empower visionary platforms');
insert into Categoria (id, name, description) values (9, 'Finance', 'e-enable efficient paradigms');
insert into Categoria (id, name, description) values (10, 'Finance', 'synergize enterprise applications');
insert into Categoria (id, name, description) values (11, 'n/a', 'seize compelling supply-chains');
insert into Categoria (id, name, description) values (12, 'Health Care', 'visualize back-end models');
insert into Categoria (id, name, description) values (13, 'Public Utilities', 'facilitate 24/7 relationships');
insert into Categoria (id, name, description) values (14, 'Public Utilities', 'engineer 24/7 synergies');
insert into Categoria (id, name, description) values (15, 'n/a', 'engineer integrated bandwidth');
insert into Categoria (id, name, description) values (16, 'Energy', 'aggregate extensible portals');
insert into Categoria (id, name, description) values (17, 'Consumer Durables', 'unleash frictionless experiences');
insert into Categoria (id, name, description) values (18, 'Capital Goods', 'matrix 24/7 schemas');
insert into Categoria (id, name, description) values (19, 'Transportation', 'monetize e-business niches');
insert into Categoria (id, name, description) values (20, 'Consumer Durables', 'disintermediate proactive infrastructures');
insert into Categoria (id, name, description) values (21, 'Health Care', 'innovate innovative relationships');
insert into Categoria (id, name, description) values (22, 'n/a', 'strategize transparent interfaces');
insert into Categoria (id, name, description) values (23, 'Consumer Non-Durables', 'iterate 24/365 infrastructures');
insert into Categoria (id, name, description) values (24, 'Finance', 'envisioneer enterprise applications');
insert into Categoria (id, name, description) values (25, 'Technology', 'embrace dot-com schemas');
insert into Categoria (id, name, description) values (26, 'Health Care', 'engage robust action-items');
insert into Categoria (id, name, description) values (27, 'n/a', 'leverage B2C systems');
insert into Categoria (id, name, description) values (28, 'Health Care', 'streamline vertical infomediaries');
insert into Categoria (id, name, description) values (29, 'Technology', 'e-enable proactive web services');
insert into Categoria (id, name, description) values (30, 'n/a', 'aggregate cutting-edge vortals');
insert into Categoria (id, name, description) values (31, 'Basic Industries', 'syndicate B2B methodologies');
insert into Categoria (id, name, description) values (32, 'Capital Goods', 'repurpose collaborative eyeballs');
insert into Categoria (id, name, description) values (33, 'Health Care', 'iterate cross-media e-markets');
insert into Categoria (id, name, description) values (34, 'Technology', 'extend one-to-one networks');
insert into Categoria (id, name, description) values (35, 'Finance', 'transition back-end markets');
insert into Categoria (id, name, description) values (36, 'Finance', 'expedite granular infomediaries');
insert into Categoria (id, name, description) values (37, 'Miscellaneous', 'architect impactful experiences');
insert into Categoria (id, name, description) values (38, 'Finance', 'monetize virtual schemas');
insert into Categoria (id, name, description) values (39, 'Consumer Durables', 'brand scalable models');
insert into Categoria (id, name, description) values (40, 'Finance', 'transition cross-platform portals');
insert into Categoria (id, name, description) values (41, 'Finance', 'aggregate extensible interfaces');
insert into Categoria (id, name, description) values (42, 'Health Care', 'strategize bricks-and-clicks deliverables');
insert into Categoria (id, name, description) values (43, 'n/a', 'revolutionize synergistic models');
insert into Categoria (id, name, description) values (44, 'Finance', 'synergize bleeding-edge synergies');
insert into Categoria (id, name, description) values (45, 'Health Care', 'scale back-end users');
insert into Categoria (id, name, description) values (46, 'n/a', 'utilize collaborative web services');
insert into Categoria (id, name, description) values (47, 'Finance', 'unleash rich experiences');
insert into Categoria (id, name, description) values (48, 'Health Care', 'seize best-of-breed channels');
insert into Categoria (id, name, description) values (49, 'n/a', 'syndicate ubiquitous markets');
insert into Categoria (id, name, description) values (50, 'Finance', 'syndicate world-class portals');
insert into Categoria (id, name, description) values (51, 'Consumer Services', 'productize best-of-breed solutions');
insert into Categoria (id, name, description) values (52, 'Public Utilities', 'benchmark plug-and-play vortals');
insert into Categoria (id, name, description) values (53, 'n/a', 'reintermediate out-of-the-box e-markets');
insert into Categoria (id, name, description) values (54, 'n/a', 'architect cross-media solutions');
insert into Categoria (id, name, description) values (55, 'Finance', 'incentivize world-class applications');
insert into Categoria (id, name, description) values (56, 'Health Care', 'revolutionize revolutionary initiatives');
insert into Categoria (id, name, description) values (57, 'n/a', 'engineer cutting-edge action-items');
insert into Categoria (id, name, description) values (58, 'Consumer Durables', 'reinvent web-enabled eyeballs');
insert into Categoria (id, name, description) values (59, 'Capital Goods', 'harness ubiquitous systems');
insert into Categoria (id, name, description) values (60, 'Finance', 'extend global e-tailers');
insert into Categoria (id, name, description) values (61, 'Finance', 'integrate interactive content');
insert into Categoria (id, name, description) values (62, 'Health Care', 'syndicate end-to-end vortals');
insert into Categoria (id, name, description) values (63, 'Public Utilities', 'incentivize robust e-tailers');
insert into Categoria (id, name, description) values (64, 'Basic Industries', 'orchestrate cross-media web services');
insert into Categoria (id, name, description) values (65, 'n/a', 'incentivize B2C niches');
insert into Categoria (id, name, description) values (66, 'Health Care', 'morph seamless content');
insert into Categoria (id, name, description) values (67, 'Energy', 'repurpose customized schemas');
insert into Categoria (id, name, description) values (68, 'Finance', 'engineer transparent solutions');
insert into Categoria (id, name, description) values (69, 'Health Care', 'seize synergistic web services');
insert into Categoria (id, name, description) values (70, 'Technology', 'syndicate cross-media systems');
insert into Categoria (id, name, description) values (71, 'Health Care', 'repurpose out-of-the-box relationships');
insert into Categoria (id, name, description) values (72, 'Finance', 'repurpose cutting-edge bandwidth');
insert into Categoria (id, name, description) values (73, 'Consumer Non-Durables', 'exploit magnetic synergies');
insert into Categoria (id, name, description) values (74, 'n/a', 'incubate world-class markets');
insert into Categoria (id, name, description) values (75, 'Capital Goods', 'morph bleeding-edge channels');
insert into Categoria (id, name, description) values (76, 'Energy', 'strategize 24/7 infomediaries');
insert into Categoria (id, name, description) values (77, 'n/a', 'recontextualize granular methodologies');
insert into Categoria (id, name, description) values (78, 'Health Care', 'matrix end-to-end ROI');
insert into Categoria (id, name, description) values (79, 'Finance', 'expedite sticky convergence');
insert into Categoria (id, name, description) values (80, 'Technology', 'seize bleeding-edge infrastructures');
insert into Categoria (id, name, description) values (81, 'Miscellaneous', 'utilize distributed channels');
insert into Categoria (id, name, description) values (82, 'Technology', 'maximize distributed e-tailers');
insert into Categoria (id, name, description) values (83, 'Consumer Services', 'synthesize compelling initiatives');
insert into Categoria (id, name, description) values (84, 'n/a', 'evolve world-class relationships');
insert into Categoria (id, name, description) values (85, 'n/a', 'syndicate seamless applications');
insert into Categoria (id, name, description) values (86, 'Finance', 'streamline innovative users');
insert into Categoria (id, name, description) values (87, 'n/a', 'utilize viral platforms');
insert into Categoria (id, name, description) values (88, 'Consumer Services', 'enable intuitive ROI');
insert into Categoria (id, name, description) values (89, 'n/a', 'harness extensible communities');
insert into Categoria (id, name, description) values (90, 'Energy', 'e-enable granular bandwidth');
insert into Categoria (id, name, description) values (91, 'n/a', 'repurpose robust metrics');
insert into Categoria (id, name, description) values (92, 'Finance', 'morph intuitive e-business');
insert into Categoria (id, name, description) values (93, 'Technology', 'evolve efficient infomediaries');
insert into Categoria (id, name, description) values (94, 'Basic Industries', 'mesh sticky infrastructures');
insert into Categoria (id, name, description) values (95, 'Health Care', 'productize virtual vortals');
insert into Categoria (id, name, description) values (96, 'Finance', 'strategize dynamic initiatives');
insert into Categoria (id, name, description) values (97, 'n/a', 'incentivize one-to-one web services');
insert into Categoria (id, name, description) values (98, 'n/a', 'drive rich interfaces');
insert into Categoria (id, name, description) values (99, 'Consumer Services', 'whiteboard open-source content');
insert into Categoria (id, name, description) values (100, 'Health Care', 'transition cross-platform channels');
